version: '3'

services:
    server:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/dashboard
#        depends_on:
#            - mongodb
#    mongodb:
#        image: mongo:latest
#        ports:
#            - "27017:27017"
#        command: --smallfiles --logpath /dev/null
